spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring-boot-immutables-map-struct-demo
logging:
  level:
    ROOT: debug
server:
  error:
    include-binding-errors: always
    include-message: always
